use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::neuron_config::NeuronConfig;
use crate::paths::store_root;

const TEMPLATE: &str = r#"# neuron.yaml — generated by `neuron init`
name: my-llm-project
version: "1.0"

model:
  name: meta-llama/Meta-Llama-3-8B-Instruct
  source: huggingface   # huggingface | hf | local | path
  # Local model example (HF-like folder, LoRA, or .gguf / .safetensors file):
  # name: ./weights
  # source: local
  quantization: null

runtime:
  python: "3.11"
  mode: host          # host | oci (Docker + mounts; Linux + NVIDIA Container Toolkit)
  cuda: "12.1"
  packages:
    - transformers==4.40.0
    - peft==0.10.0
    - datasets==2.19.0
    - trl==0.8.6

gpu:
  min_vram: 16gb
  strategy: single

# Uncomment for Docker isolation (see also `neuron run --oci`):
# container:
#   image: nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04
#   executor: docker   # docker | runc (runc: `neuron oci prepare`)

entrypoint: train.py

env:
  HF_TOKEN: "${HF_TOKEN}"
  BATCH_SIZE: "4"
"#;

/// Available templates in specs/examples/
const AVAILABLE_TEMPLATES: &[&str] = &["inference", "finetune", "local-model"];

/// Get the path to a template file.
fn template_path(name: &str) -> Option<PathBuf> {
    // Try relative to the binary (dev layout)
    let exe = std::env::current_exe().ok()?;
    let repo_root = exe.parent()?.parent()?.parent()?;
    let template_file = repo_root
        .join("specs/examples")
        .join(format!("{}.yaml", name));
    if template_file.exists() {
        return Some(template_file);
    }

    // Try CARGO_MANIFEST_DIR (for tests)
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let template_file = manifest_dir
        .join("../specs/examples")
        .join(format!("{}.yaml", name));
    if template_file.exists() {
        return Some(template_file);
    }

    None
}

#[allow(dead_code)]
pub fn init_interactive() -> Result<()> {
    init_with_template(None)
}

pub fn init_with_template(template: Option<&str>) -> Result<()> {
    let cwd = std::env::current_dir()?;
    let yaml_path = cwd.join("neuron.yaml");
    if yaml_path.exists() {
        anyhow::bail!("neuron.yaml already exists in this directory.");
    }

    let content = match template {
        Some(name) => {
            if let Some(path) = template_path(name) {
                std::fs::read_to_string(&path)
                    .with_context(|| format!("read template {:?}", path))?
            } else {
                anyhow::bail!(
                    "Template '{}' not found. Available templates: {}",
                    name,
                    AVAILABLE_TEMPLATES.join(", ")
                );
            }
        }
        None => TEMPLATE.to_string(),
    };

    std::fs::write(&yaml_path, &content).with_context(|| format!("write {:?}", yaml_path))?;

    let _ = store_root();
    std::fs::create_dir_all(store_root()).ok();

    println!("Created {:?}.", yaml_path);
    if let Some(t) = template {
        println!("Template: {}", t);
    }
    println!("Edit `model.name`, `entrypoint`, and `gpu.min_vram` for your machine.");
    println!("Global store: {:?}", store_root());

    // Validate generated YAML
    let _cfg: NeuronConfig = NeuronConfig::load_path(&yaml_path)?;
    Ok(())
}

/// List available templates.
pub fn list_templates() {
    println!("Available templates:");
    for t in AVAILABLE_TEMPLATES {
        println!("  - {}", t);
    }
    println!("\nUsage: neuron init --template <name>");
}

pub fn default_yaml_path() -> std::path::PathBuf {
    Path::new("neuron.yaml").to_path_buf()
}
