use std::path::Path;

use anyhow::{Context, Result};

use crate::neuron_config::NeuronConfig;
use crate::paths::store_root;

const TEMPLATE: &str = r#"# neuron.yaml — generated by `neuron init`
name: my-llm-project
version: "1.0"

model:
  name: meta-llama/Meta-Llama-3-8B-Instruct
  source: huggingface   # huggingface | hf | local | path
  # Local model example (HF-like folder, LoRA, or .gguf / .safetensors file):
  # name: ./weights
  # source: local
  quantization: null

runtime:
  python: "3.11"
  mode: host          # host | oci (Docker + mounts; Linux + NVIDIA Container Toolkit)
  cuda: "12.1"
  packages:
    - transformers==4.40.0
    - peft==0.10.0
    - datasets==2.19.0
    - trl==0.8.6

gpu:
  min_vram: 16gb
  strategy: single

# Uncomment for Docker isolation (see also `neuron run --oci`):
# container:
#   image: nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04
#   executor: docker   # docker | runc (runc: `neuron oci prepare`)

entrypoint: train.py

env:
  HF_TOKEN: "${HF_TOKEN}"
  BATCH_SIZE: "4"
"#;

pub fn init_interactive() -> Result<()> {
    let cwd = std::env::current_dir()?;
    let yaml_path = cwd.join("neuron.yaml");
    if yaml_path.exists() {
        anyhow::bail!("neuron.yaml already exists in this directory.");
    }
    std::fs::write(&yaml_path, TEMPLATE).with_context(|| format!("write {:?}", yaml_path))?;

    let _ = store_root();
    std::fs::create_dir_all(store_root()).ok();

    println!("Created {:?}.", yaml_path);
    println!("Edit `model.name`, `entrypoint`, and `gpu.min_vram` for your machine.");
    println!("Global store: {:?}", store_root());

    // Validate generated YAML
    let _cfg: NeuronConfig = NeuronConfig::load_path(&yaml_path)?;
    Ok(())
}

pub fn default_yaml_path() -> std::path::PathBuf {
    Path::new("neuron.yaml").to_path_buf()
}
