pub mod dashboard;
mod dashboard_demo;
pub mod doctor;
pub mod gpu_cmd;
pub mod host_cmd;
pub mod init;
pub mod lock;
pub mod model;
pub mod oci_cmd;
pub mod pull;
pub mod run;
pub mod serve;
pub mod stats;
pub mod swap;
pub mod welcome;
